/** @type {import('tailwindcss').Config} */
export default {
    content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}', './public/**/*.html'],
    theme: {
        extend: {
            fontSize: {
                xs: ["0.75rem", { lineHeight: "1.25", letterSpacing: "0.02em", fontWeight: "400" }],
                sm: ["0.875rem", { lineHeight: "1.35", letterSpacing: "0.02em", fontWeight: "400" }],
                base: ["1rem", { lineHeight: "1.5", letterSpacing: "0.025em", fontWeight: "400" }],
                lg: ["1.125rem", { lineHeight: "1.5", letterSpacing: "0.025em", fontWeight: "500" }],
                xl: ["1.25rem", { lineHeight: "1.5", letterSpacing: "0.03em", fontWeight: "600" }],
                "2xl": ["1.5rem", { lineHeight: "1.4", letterSpacing: "0.03em", fontWeight: "600" }],
                "3xl": ["1.875rem", { lineHeight: "1.3", letterSpacing: "0.03em", fontWeight: "700" }],
                "4xl": ["2.25rem", { lineHeight: "1.2", letterSpacing: "0.035em", fontWeight: "700" }],
                "5xl": ["3rem", { lineHeight: "1.1", letterSpacing: "0.04em", fontWeight: "800" }],
                "6xl": ["3.75rem", { lineHeight: "1.1", letterSpacing: "0.04em", fontWeight: "800" }],
                "7xl": ["4.5rem", { lineHeight: "1", letterSpacing: "0.045em", fontWeight: "900" }],
                "8xl": ["6rem", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "900" }],
                "9xl": ["8rem", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "900" }],
            },
            fontFamily: {
                heading: ["syne"],
                paragraph: ["barlow-extralight"]
            },
            colors: {
                primary: "#0A66C2",
                "primary-foreground": "#FFFFFF",
                secondary: "#0A8CFF",
                "secondary-foreground": "#E7F1FF",
                background: "#FFFFFF",
                brandaccent: "#0A66C2",
                buttonbackground: "#0A66C2",
                foreground: "#000000",
                destructive: "#DC3545",
                destructiveforeground: "#ffffff",
                iconcolor: "#65676B",
                contentblockbackground: "#F2F2F2",
                buttonoutline: "#0A66C2",
                cardbackground: "#FFFFFF",
                textprimary: "#000000",
                inputbackground: "#FFFFFF",
                inputborder: "#D5D9E0",
                buttonforeground: "#FFFFFF",
                darktext: "#000000",
                buttonborder: "#0A66C2",
                "contentblockbackground-custom": "#F2F2F2",
                "secondary-foreground-new": "#E7F1FF",
                "secondary-foreground-old": "#E7F1FF",
                "secondary-foreground-token": "#E7F1FF",
                "linkedin-blue": "#0A66C2",
                "linkedin-blue-dark": "#004182",
                "linkedin-blue-light": "#0A8CFF",
                "linkedin-gray": "#65676B",
                "linkedin-gray-light": "#D5D9E0",
                "linkedin-success": "#0A8617",
                "linkedin-warning": "#F5A623",
                "linkedin-error": "#DC3545"
            },
        },
    },
    future: {
        hoverOnlyWhenSupported: true,
    },
    plugins: [require('@tailwindcss/container-queries'), require('@tailwindcss/typography')],
}
